os: Visual Studio 2015

build_script:
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - msbuild "HashCheck.sln" /m /p:Configuration=Release;Platform=Win32
  - msbuild "HashCheck.sln" /m /p:Configuration=Release;Platform=x64

after_build:
  - cd "%APPVEYOR_BUILD_FOLDER%\installer"
  - '"C:\Program Files (x86)\NSIS\bin\makensis.exe" "HashCheck.nsi"'
  - copy "HashCheckSetup.exe" "%APPVEYOR_BUILD_FOLDER%"
  - 'powershell -Command "& { $hash = (Get-FileHash -Algorithm SHA256 "HashCheckSetup.exe").hash; Write-Host $hash " *HashCheckSetup.exe"; }" > "HashCheckSetup.exe.sha256"'
  - copy "HashCheckSetup.exe.sha256" "%APPVEYOR_BUILD_FOLDER%"

artifacts:
  - path: HashCheckSetup.exe
    name: installer
  - path: HashCheckSetup.exe.sha256
    name: checksum
